### ISSUE TITLE
Resignation threshold

### ISSUE THREAD

**Issue by francogrex** [kobanium/Ray#151]
This is a great engine. Is there a way to adjust the threshold of the engine resigning? I find that it rather resigns too quickly - when playing against other engines of course, not myself I always lose against it. Thanks

**Comment by zakki** [comment]
`RESIGN_THRESHOLD` is hard coded, so you need to edit source code and build it.
https://github.com/search?q=repo%3Akobanium%2FRay%20RESIGN_THRESHOLD&type=code

I added a gtp command to change these parameters via gtp console, but it is for previous version Ray.
https://github.com/zakki/Ray/blame/nn/src/Gtp.cpp#L871

**Comment by kobanium** [comment]
I think it would be better to be able to set resignation threshold, so I will implement the command line option for resignation threshold.

**Comment by kobanium** [comment]
I implemented ```--resign``` command line option, and released v10.2.0. Please download v10.2.0.

**Comment by francogrex** [comment]
Excellent.
