### ISSUE TITLE
Compiling  error in V.S 2019 windows 10 system

### ISSUE THREAD

**Issue by jun63cn** [kobanium/Ray#156]
![Snipaste_2024-01-15_23-08-35](https://github.com/kobanium/Ray/assets/30382868/119464e2-abea-4c6b-b310-0080a52c8178)
![Snipaste_2024-01-15_23-09-51](https://github.com/kobanium/Ray/assets/30382868/82ef8b5a-314b-4a22-90cd-065015cfa275)
Need help. Thanks

**Comment by kobanium** [comment]
I'm sorry I did not test on Windows.  But I can fix these errors.
I'm preparing v10.3.0 release now, so I'll fix the errors as best I can.

**Comment by kobanium** [comment]
I fixed these errors, but I did not test compling on Windows OS.
Please download v10.3.0 and try to compile

**Comment by jun63cn** [comment]
It's great ! Thank you very much.    But there's still errors in UctRating.  
![Snipaste_2024-01-18_09-38-41](https://github.com/kobanium/Ray/assets/30382868/5e2e57b5-f045-469d-a8fe-ba2d3b18d932)

**Comment by kobanium** [comment]
I'm sorry there are typo and incorrect variable declaration.
I fixed UctRating.cpp and updated v10.3.0 release. Please download new source files and try compiling.

**Comment by jun63cn** [comment]
Excellent.  It‘ ’OK now。Thanks
