### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by jun63cn** [kobanium/Ray#165]
Hi， I found an unexpected crash after the move by ray version 11 and 10.3.  the ray9.01 is OK.   Thanks.
![Snipaste_2024-01-29_23-21-14](https://github.com/kobanium/Ray/assets/30382868/a2393e50-373a-4e23-9e33-b1e6a879313e)
[err.zip](https://github.com/kobanium/Ray/files/14086662/err.zip)
[e2.sgf.zip](https://github.com/kobanium/Ray/files/14096890/e2.sgf.zip)

**Comment by kobanium** [comment]
Thanks for the report.  
But I cannot reproduce these crashes, so please tell me following information,
 - Command line options
 - Operation System

If you can reproduce this crash issue, would you attach GTP shell messages ?

**Comment by jun63cn** [comment]
The O.S is windows 10 professional 22H2. Using gogui.jar load Ray11. and open err.sgf goto the last move. Let Ray play white then crash without anything. the shell.log is attached.   Thanks
![Snipaste_2024-01-31_11-55-15](https://github.com/kobanium/Ray/assets/30382868/411d6c82-dc69-4077-949c-2c6e962ef30a)
[shell.log](https://github.com/kobanium/Ray/files/14107491/shell.log)

**Comment by jun63cn** [comment]
It's great!  This issue  has solved. Thank you very much!
