### ISSUE TITLE
Ray cannot treat draw simulations

### ISSUE THREAD

**Issue by kobanium** [kobanium/Ray#60]
Ray assumes that komi is floating point.
It causes unstable behavior when komi is a integer number.

**Comment by wpstmxhs** [comment]
I think your fix is not stable.
When there are only best moves to make the game result in draw, Ray should play that best move.
But emulating it from 1/2 chance of uniform random generator, doesn't guarantee working correctly.
I think draw situation should be treated as winning situation.
It should make Ray play more stable.

**Comment by kobanium** [comment]
Thanks your opinion. I forgot 1pt komi disadvantage setting. 
If Ray recognizes a game is draw, it means Ray is winner and score is +1 for Ray.
I just fixed treating draw situation.
