### ISSUE TITLE
Can't run ray9.0

### ISSUE THREAD

**Issue by jun63cn** [kobanium/Ray#67]
After add SearchBoard.cpp in include  I  suceed compiled it on VC++2015.  but ray.exe  crashed when I type genmove b. Don't know why

**Comment by kobanium** [comment]
Please tell me error messages or give me screenshots.

**Comment by jun63cn** [comment]
![err](https://user-images.githubusercontent.com/30382868/28504259-708fa588-7046-11e7-831b-0b15f872b720.jpg)

**Comment by jun63cn** [comment]
![err2](https://user-images.githubusercontent.com/30382868/28505026-0e14fc44-7052-11e7-873b-b677f0d2e61f.jpg)
The problem seems in ladder.cpp.  thanks anyway!

**Comment by zakki** [comment]
`search_game_info_t` is too large on stack.
Replacing `search_game_info_t  ladder_game;` to `auto ladder_game = make_unique<search_game_info_t>();` seems to work well.
